server:
  port: 28764
  servlet:
    context-path: /payService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

spring:
  profiles:
    active: dev
  application:
    name: pay-service
  cloud:
    config:
      #      discovery:
      #        enabled: true
      #        service-id: config-service
      uri: http://localhost:8760/configService
      #      profile: dev
      #      label: master
      fail-fast: true
      name: ${spring.application.name}
  #      username: user
  #      password: fxq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

feign:
  hystrix:
    enabled: true

logging:
  path: logs
  file:
    file: /study_springcloud_pay.log
    file.max-size: 100MB
    file.max-history: 10
  level:
    root: info

config:
  test: test11
